# Generated by Django 4.2.7 on 2023-11-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('one_hour_change', models.DecimalField(decimal_places=2, max_digits=5)),
                ('one_hour_flag', models.IntegerField()),
                ('twenty_four_hour_change', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twenty_four_hour_flag', models.IntegerField()),
                ('market_cap', models.BigIntegerField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
    ]
