# Generated by Django 4.2.7 on 2023-11-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_user_groups_user_id_or_photo_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_or_photo',
        ),
    ]
