# Generated by Django 4.2.7 on 2023-11-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_remove_user_id_or_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_or_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_or_photo/'),
        ),
    ]
