# Generated by Django 4.2.7 on 2023-11-20 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_user_id_or_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crypto',
        ),
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
